### ISSUE TITLE
Thread sanitizer job frequently fails with 'java.lang.OutOfMemoryError: Java heap space'

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ci#265]
Memory usage is high, higher than it should be (JVM is allotted a maximum heap size of 10G on a 16G instance) on the CI host but I am still verifying whether the OutOfMemoryError is on the Jenkins master rather than the agent JVM process.

Introduced in #254 and is blocking ros2/ros2#666 :imp: 

<details><summary>Jenkins stacktrace</summary>
<code><pre>
ERROR: Step ‘Publish xUnit test result report’ aborted due to exception:
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl.getNodeValueString(DeferredDocumentImpl.java:1181)
        at com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl.getNodeValueString(DeferredDocumentImpl.java:1134)
        at com.sun.org.apache.xerces.internal.dom.DeferredTextImpl.synchronizeData(DeferredTextImpl.java:96)
        at com.sun.org.apache.xerces.internal.dom.CharacterDataImpl.getNodeValue(CharacterDataImpl.java:91)
        at net.sf.saxon.dom.NodeWrapper.getStringValueCS(NodeWrapper.java:364)
        at net.sf.saxon.om.Navigator.copy(Navigator.java:587)
        at net.sf.saxon.dom.NodeWrapper.copy(NodeWrapper.java:848)
        at net.sf.saxon.om.Navigator.copy(Navigator.java:570)
        at net.sf.saxon.dom.NodeWrapper.copy(NodeWrapper.java:848)
        at net.sf.saxon.om.Navigator.copy(Navigator.java:570)
        at net.sf.saxon.dom.NodeWrapper.copy(NodeWrapper.java:848)
        at net.sf.saxon.om.Navigator.copy(Navigator.java:570)
        at net.sf.saxon.dom.NodeWrapper.copy(NodeWrapper.java:848)
        at net.sf.saxon.om.Navigator.copy(Navigator.java:570)
        at net.sf.saxon.dom.NodeWrapper.copy(NodeWrapper.java:848)
        at net.sf.saxon.om.Navigator.copy(Navigator.java:570)
        at net.sf.saxon.dom.NodeWrapper.copy(NodeWrapper.java:848)
        at net.sf.saxon.om.Navigator.copy(Navigator.java:570)
        at net.sf.saxon.dom.NodeWrapper.copy(NodeWrapper.java:848)
        at net.sf.saxon.event.DocumentSender.send(DocumentSender.java:54)
        at net.sf.saxon.event.Sender.sendDocumentInfo(Sender.java:278)
        at net.sf.saxon.event.Sender.send(Sender.java:177)
        at net.sf.saxon.event.Sender.send(Sender.java:50)
        at net.sf.saxon.Configuration.buildDocument(Configuration.java:2973)
        at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:287)
        at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:331)
        at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:172)
        at org.jenkinsci.lib.dtkit.model.InputMetricXSL.convert(InputMetricXSL.java:181)
Caused: java.io.IOException: Remote call on JNLP4-connect connection from ip-172-30-0-91.ec2.internal/172.30.0.91:59622 failed
        at hudson.remoting.Channel.call(Channel.java:961)
        at hudson.FilePath.act(FilePath.java:1072)
        at hudson.FilePath.act(FilePath.java:1061)
        at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
        at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
        at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
        at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
        at hudson.model.Build$BuildExecution.post2(Build.java:186)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
        at hudson.model.Run.execute(Run.java:1835)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
</pre></code>
</details>

**Comment by nuclearsandwich** [comment]
At first I thought something was happening with the retest count with so many tests but since the thread sanitizer job doesn't retest anything I was just getting very lucky that all of my manual CI jobs succeeded while all of the nightlies have failed. As of today I can reproduce failures with manual CI as well.

**Comment by nuclearsandwich** [comment]
Looking at the test output on disk, it looks like test_rcpcpp is generating a ~200M CTest Test.xml file. I've started [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6481)](https://ci.ros2.org/job/ci_linux/6481/) which tests only test_communication (which itself generates a ~30M Test.xml file). For comparison the largest of these files on other jobs I could find is 770K. If the above build passes, I'll open a PR to reduce the test scope of the thread sanitizer job to just test_communication for now. Then we can expand it once the report output is reduced.
