### ISSUE TITLE
Shebang lines not re-written for executables in libexec

### ISSUE THREAD

**Issue by dhood** [ros2/ci#87]
Our packaging jobs re-write shebang lines to be portable, however it only seems to do so for files installed to 'bin': https://github.com/ros2/ci/blob/af70aa2b8c6682b97fa286e574e33172dcc04980/ros2_batch_job/packaging.py#L118

Since we install executables to "libexec" as of late, this causes the packaged binaries to give this error (OS X):

```
$ ros2 run demo_nodes_py talker
Traceback (most recent call last):
  File "/Users/dhood/Downloads/ros2-osx-june25-2017/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.0.0', 'console_scripts', 'ros2')()
  File "/Users/dhood/Downloads/ros2-osx-june25-2017/lib/python3.6/site-packages/ros2cli/cli.py", line 64, in main
    rc = extension.main(parser=parser, args=args)
  File "/Users/dhood/Downloads/ros2-osx-june25-2017/lib/python3.6/site-packages/ros2run/command/run.py", line 59, in main
    return run_executable(path=path, argv=args.argv)
  File "/Users/dhood/Downloads/ros2-osx-june25-2017/lib/python3.6/site-packages/ros2run/api/__init__.py", line 75, in run_executable
    completed_process = subprocess.run([path] + argv)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dhood/Downloads/ros2-osx-june25-2017/lib/demo_nodes_py/talker'

$ cat /Users/dhood/Downloads/ros2-osx-june25-2017/lib/demo_nodes_py/talker
#!/Users/osrf/jenkins/workspace/packaging_osx/venv/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'demo-nodes-py==0.0.0','console_scripts','talker'
__requires__ = 'demo-nodes-py==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('demo-nodes-py==0.0.0', 'console_scripts', 'talker')()
    )
```

**Comment by dhood** [comment]
I'll update the packaging job to crawl lib in addition to bin when re-writing the shebang line.

**Comment by dhood** [comment]
resolved by https://github.com/ros2/ci/pull/88
